### ISSUE TITLE
implement _attemptRest in janus_client

### ISSUE THREAD

**Issue by JonasWijne** [shivanshtalwar0/flutter_janus_client#1]
I have a Janus Server only accessable with https

---

How can this be implemented?

**Comment by shivanshtalwar0** [comment]
It should work with both https and http see example and change serverurl value to your server's websocket url closing this since its not an issue

**Comment by JonasWijne** [comment]
hi thanks for the quick response (2 min :+1: )

---

I can see that _attemptWebSocket is implemented, but not _attemptRest i think i can just do a POST call to  /janus over http(s) and body { "janus": "create", "transaction": "any random hash" }

**Comment by shivanshtalwar0** [comment]
Sure! you are more than welcome to implement the rest functionality, once implemented open pr i will review and merge it

**Comment by shivanshtalwar0** [comment]
I personally feel working with websocket is more efficient so i implemented just the websocket part first
