### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by aevzp** [shivanshtalwar0/flutter_janus_client#11]
Firstly. Thank you for this huge work which you did!

I use this library for stream and when I want close my session I call `janusClient.destroy()` method, but still get a messages:
```
I/flutter (13515): polling active
I/flutter (13515): _eventHandler
I/flutter (13515): [{janus: keepalive}]
I/flutter (13515): handle event called
I/flutter (13515): {janus: keepalive}
I/flutter (13515): Got a keepalive on session 6432391342667273
I/flutter (13515): Long poll...
```

Am I missed something?

**Comment by shivanshtalwar0** [comment]
Hmm, seems like a potential memory leak, will fix it soon in next release

**Comment by shivanshtalwar0** [comment]
@aevzp  can you please test and see if this issue is resolved or not? also audio bridge is supported now

**Comment by aevzp** [comment]
Great! Thank you for update!

I have some trouble with lunch library with `flutter_webrtc-0.5.7`:

`
../../Library/flutter/.pub-cache/git/flutter_janus_client-ca276fd4942bf2e533883699a1a32e0aaeed2f08/lib/Plugin.dart:308:46: Error: The getter 'length' isn't defined for the class 'Future<List<RTCRtpTransceiver>>'.
 - 'Future' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'RTCRtpTransceiver' is from 'package:flutter_webrtc/src/interface/rtc_rtp_transceiver.dart' ('../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.5.7/lib/src/interface/rtc_rtp_transceiver.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'length'.
    if (transceivers != null && transceivers.length > 0) {
`

**Comment by aevzp** [comment]
I fixed that.

`Plugin.dart`
In this method need to add `await`:
```
  Future prepareTranscievers(bool offer) async {
    RTCRtpTransceiver audioTransceiver;
    RTCRtpTransceiver videoTransceiver;
    var transceivers = **await** _webRTCHandle.pc.transceivers;
```

`janus_client`:
Need a little fix in two places. Method `attach`:
```
...
        event.track.onEnded = () async {
          if (webRTCHandle.remoteStream != null) {
            webRTCHandle.remoteStream.removeTrack(event.track);
            var mid = event.track.id;
            **var transceiverRaw = await peerConnection.transceivers;
            var transceiver = transceiverRaw.firstWhere((element) => element.receiver.track == event.track);**
            mid = transceiver.mid;
            plugin.onRemoteTrack(event.streams[0], event.track, mid, false);
          }
        };
        event.track.onMute = () async {
          if (webRTCHandle.remoteStream != null) {
            webRTCHandle.remoteStream.removeTrack(event.track);
            var mid = event.track.id;
            **var transceiverRaw = await peerConnection.transceivers;
            var transceiver = transceiverRaw.firstWhere((element) => element.receiver.track == event.track);**
            mid = transceiver.mid;
            plugin.onRemoteTrack(event.streams[0], event.track, mid, false);
          }
        };
...
```

**Comment by aevzp** [comment]
Method destroy totally work for now! =) 
Thank you.

**Comment by shivanshtalwar0** [comment]
Hmm actually I haven't got time to test and improve streaming with unified plan if you think changes proposed by you will work with other plugins aswell in Unified plan then you are welcome to open a pull request

**Comment by shivanshtalwar0** [comment]
About the issue on flutter webrtc you should open issue on their repository they can give you better insights about the problem under observation
Closing this issue for now in future if you encounter any other issues related to memory leak feel free to open it again
