### ISSUE TITLE
Sound output

### ISSUE THREAD

**Issue by aevzp** [shivanshtalwar0/flutter_janus_client#15]
When we start a stream, the sound goes to the "in-call" volume control.
Is it possible to route audio to the "media" volume control? Interested in such an opportunity on Android devices.

Thank you

**Comment by shivanshtalwar0** [comment]
I think for better user experience such notification is integrated in native webrtc stack and since janus uses peer connection(webrtc stack) for any kind of operations including streaming, i don't think it would be possible, but if you find a way please do let me know. Untill then i am closing it
