### ISSUE TITLE
How to gain already created session id and handle id? 

### ISSUE THREAD

**Issue by xyzbilal** [shivanshtalwar0/flutter_janus_client#22]
Hi,
This is not an issue but info request. 
I have an application that works with freepbx voice central. everything works fine while app is in foreground. now I want to add voip notifications so that  app can receive even if app is totaly closed. 
in janus gateway I dont kill session and its active. when I call reconnect function  when new call from other extension and its in ringing state; this function claims session  but reconnect function creates new handle id and new call cant be received by app.   
I just wonder if any logic to receive current call when app starts. any idea will be appriciated. 
thanks.

**Comment by shivanshtalwar0** [comment]
closing it for now! Maybe someone from Meetcho Google Group can answer your question
