### ISSUE TITLE
WEBSOCKET

### ISSUE THREAD

**Issue by kzawadi** [shivanshtalwar0/flutter_janus_client#24]
I have this weird problem....when I use HTTP everything goes well the keep alive is pinging and fine But when I use websocket....i connect and everything goes well but after 60 seconds (Defualt janus timeout) the session get terminated..(session timeout)...

if i switch to HTTP everything is fine so i think and i can HTTP sending those keepalive packets....is anything wrong

**Comment by shivanshtalwar0** [comment]
Yes i am aware of this issue i would advise you to try v2 branch which is stable and features brand new api 
Soon i am going to deprecate previous version

**Comment by shivanshtalwar0** [comment]
For example of how v2 api works kindly check
[Videoroom_v2](https://github.com/shivanshtalwar0/flutter_janus_client/blob/v2/example/lib/VideoRoom_V2.dart)

**Comment by kzawadi** [comment]
okay i see ..nice work my man .... though no pub update as of now I have tried getting this update through git but 

Because every version of flutter_test from sdk depends on stream_channel 2.1.0-nullsafety.1 and every version of janus_client from git depends on stream_channel ^2.1.0, flutter_test from sdk is incompatible with janus_client from git.

**Comment by shivanshtalwar0** [comment]
> okay i see ..nice work my man .... though no pub update as of now I have tried getting this update through git but
> 
> Because every version of flutter_test from sdk depends on stream_channel 2.1.0-nullsafety.1 and every version of janus_client from git depends on stream_channel ^2.1.0, flutter_test from sdk is incompatible with janus_client from git.

this issue is fixed now in this [commit](https://github.com/shivanshtalwar0/flutter_janus_client/commit/97f1819a3d7549cf1fdf7851374c7b55eb19835e)
also it now fully supports videoroom using v2 api, i would highly recommend playing with it. 
let me know your experience with it! :)

**Comment by kzawadi** [comment]
nice one... I like the new janusSession and plugin API  it gives more granular controls .....the previous one you have to kinder nest functions a lot...but also the previous one(plugin class) had this "onRemoteStream" which is now I think deprecated and instead I think to get a remote stream you have to  "plugin.webRTCHandle.peerConnection.onAddStream" .....in audio bridge its quite confusing  as is it the same thing coming out as previous version (onRemoteStream) or what ...i need clarifications as Janus audio bridge already mixes all peer audio (MCU) so onaddstream will the stream be added when another peer join or is it just the first time it connects......(English second language)

**Comment by shivanshtalwar0** [comment]
Yes everything related to old code would be deprecated soon only example updated as of now is videoroom_v2 rest code is as it is which is still using old api version as i will develop v2 you will see old code go away piece by piece

**Comment by shivanshtalwar0** [comment]
For audio bridge example i will soon write example using new api once i am done with unified support in v2

**Comment by kzawadi** [comment]
@shivanshtalwar0   nice work man
