### ISSUE TITLE
How to test in a local network without stun and turn?

### ISSUE THREAD

**Issue by PedroRTomas** [shivanshtalwar0/flutter_janus_client#3]
Hello,
First of all, @shivanshtalwar0, thank you for taking the initiative to bring the Janus to flutter!
A quick question: I'm trying to run some tests locally and at this moment I don't own a turn or a stun server. Once 'iceServers' are mandatory, is it possible to use JanusClient constructor like this:
JanusClient(iceServers: [], server: [
        'https://my _local_ip/janus'
      ], withCredentials: false);
?
Another question: I'm using an Android phone to debug and I'm also experiencing what was mentioned here:
https://github.com/flutter-webrtc/flutter-webrtc/issues/126
Can this being happening because the connection to the server is failing? If not, what other problems may cause this?

Thanks in advance!

**Comment by shivanshtalwar0** [comment]
In my experience this doesn't seem to work without providing turn/stun server but i haven't tried to test this functionality
So you can and should use  turn/stun servers to test it as of now video room works and video call should work too since they both works in similar fashion
Dead loop that you referring to i haven't experienced in my testing that's probably because you missing stun/turn details.

**Comment by PedroRTomas** [comment]
Ok, thanks for the quick reply!
Considering this info, I will try to get and configure turn/stun server in order to overcome this problem!

**Comment by RomanIvn** [comment]
https://github.com/RomanIvn/flutter_janus_client

I've forked and modified the plugin&client to accept self-signed certificates.
I'm hosting a Janus-gateway on raspberry pi, it is configured to serve HTTPS (janus.transport.http.jcfg) With self-signed certificates. 

The ICE servers are **empty** and its working:
I'm streaming RPI's USB microphone to Janus 5002 rtp with ffmpeg and listening to the stream with the streaming example completely offline.

Thanks @shivanshtalwar0  for planting the seeds <3

**Comment by shivanshtalwar0** [comment]
@RomanIvn you should try v2 api aswell i am sure you will like it better than current api :)

**Comment by RomanIvn** [comment]
https://github.com/RomanIvn/flutter_janus_client/commit/06d94c819446a13936e5d92fb1f728afb38a0bb8

Trusing self-signed certificates on the JSON Api solves it. ICE are empy

**Comment by RomanIvn** [comment]
Yeah will move my fork over there,  
I didn't completely understood if the Streaming example (playing sound only) is supported in v2 yet  :P

**Comment by shivanshtalwar0** [comment]
It is possible to stream any media either audio or video just that i haven't written streaming example using v2 api yet as soon as i do that you will be able to use it also i will reccommend you to join our little community on gitter to discuss various features to improve the plugin

**Comment by shivanshtalwar0** [comment]
@RomanIvn  Streaming example updated using v2 api on v2 branch, kindly test it, v2 branch now supports all major plugins next step is integration of unified plan
